# version: "1.0"
# services:
#   web:
#     build: .
#     ports:
#       - "80:1080"

#   redis:
#     image: "redis:alpine"
version: "1.0"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:1080"
    depends_on:
      - redis
      - database

  redis:
    image: "redis:alpine"

  database:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "8001:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  
    depends_on:
      - prometheus

volumes:
  database-data:

